"""End-to-end smoke test of the v1 single-pass DVC pipeline.

Composes the six algorithmic stages currently landed —

    build_grid → extract_subvolumes → preprocess_subvolumes
                 → correlate → peak_displacement → gaussian_subvoxel_fit

— on a synthetic textured pair generated by
:mod:`mamba_dvc.validate.synthetic`. Asserts that the recovered
displacement at every interior POI matches the analytical ground truth
within plan §2's 0.1-voxel target.

This is the "smallest verifiable slice" called for in plan §12 step 4:
it does not yet involve mask handling, multi-GPU dispatch, or the
``DisplacementField`` orchestrator (those are upcoming work). When
``mamba_dvc.pipeline.correlate.correlate`` lands, this file should be
rewritten to call it directly and the inline composition deleted.
"""

from __future__ import annotations

import numpy as np
import pytest
from mamba_dvc.core.extract import extract_subvolumes
from mamba_dvc.core.grid import build_grid
from mamba_dvc.core.ncc import correlate, peak_displacement
from mamba_dvc.core.peakfit import gaussian_subvoxel_fit
from mamba_dvc.core.window import preprocess_subvolumes
from mamba_dvc.validate.synthetic import make_pair, rigid_shift, sample_on_grid


def _run_pipeline(
    reference: np.ndarray,
    deformed: np.ndarray,
    *,
    window: int,
    overlap: float,
    tukey_alpha: float = 0.25,
) -> tuple[np.ndarray, np.ndarray]:
    """Run the v1 single-pass slice and return ``(positions, displacements)``."""
    grid = build_grid(reference.shape, window=window, overlap=overlap)

    ref_sv = extract_subvolumes(reference, grid.starts, grid.window)
    def_sv = extract_subvolumes(deformed, grid.starts, grid.window)

    ref_pp = preprocess_subvolumes(ref_sv, None, tukey_alpha=tukey_alpha)
    def_pp = preprocess_subvolumes(def_sv, None, tukey_alpha=tukey_alpha)

    corr = correlate(ref_pp, def_pp)
    integer, _ = peak_displacement(corr)
    fractional = gaussian_subvoxel_fit(corr, integer)

    displacements = integer.astype(np.float32) + fractional
    return grid.positions, displacements


def _interior_mask(
    starts: np.ndarray,
    window: tuple[int, int, int],
    volume_shape: tuple[int, int, int],
    *,
    margin: int,
) -> np.ndarray:
    """Return a boolean mask of POIs whose subvolume sits ``margin`` voxels
    away from every face of the volume.

    The synthetic warp uses ``mode="reflect"`` boundary handling, so a
    POI whose subvolume touches the face sees reflected content instead
    of the analytically displaced texture. Excluding a margin equal to
    the maximum displacement plus a buffer keeps the assertion clean
    (plan §9 calls this out under tier-1 validation).
    """
    z0 = starts[:, 0]
    y0 = starts[:, 1]
    x0 = starts[:, 2]
    wz, wy, wx = window
    sz, sy, sx = volume_shape
    return (
        (z0 >= margin)
        & (z0 + wz <= sz - margin)
        & (y0 >= margin)
        & (y0 + wy <= sy - margin)
        & (x0 >= margin)
        & (x0 + wx <= sx - margin)
    )


@pytest.mark.slow
class TestPipelineSmoke:
    @pytest.mark.parametrize(
        "shift",
        [
            (0.3, -0.7, 1.4),
            (-1.2, 1.8, -0.4),
            (2.4, -0.6, -2.7),
        ],
    )
    def test_recovers_rigid_fractional_shift(self, shift: tuple[float, float, float]):
        # Volume sized so the grid yields several interior POIs at
        # window=64, overlap=0.5; small enough to run in CI.
        # Window 64 (rather than the plan's default 96) keeps the test
        # fast while preserving enough headroom in the SNR vs. peak-
        # locking bias to clear the 0.1-voxel target. Shifts are chosen
        # with non-trivial fractional parts on every axis so the
        # Gaussian-fit bias near integer shifts (a known limitation —
        # see plan §2 and ``docs/plans/ncc.md``) does not enter the
        # assertion.
        shape: tuple[int, int, int] = (160, 160, 160)
        window = 64
        overlap = 0.5
        pair = make_pair(shape=shape, field=rigid_shift(shift), seed=17)

        _, recovered = _run_pipeline(
            pair.reference, pair.deformed, window=window, overlap=overlap
        )
        grid = build_grid(shape, window=window, overlap=overlap)
        ground_truth = sample_on_grid(pair.field, grid)

        # Buffer the interior filter by max-shift voxels plus a few for
        # the cubic-spline boundary kernel.
        max_shift = int(np.ceil(max(abs(s) for s in shift)))
        margin = max_shift + 4
        interior = _interior_mask(grid.starts, grid.window, shape, margin=margin)
        assert interior.sum() >= 8, "interior must contain enough POIs to be meaningful"

        error = np.abs(recovered[interior] - ground_truth[interior])
        assert np.all(error < 0.1), (
            f"max error per axis: {error.max(axis=0)} (target < 0.1); "
            f"recovered example={recovered[interior][0]} expected={ground_truth[interior][0]}"
        )

    def test_recovers_zero_shift(self):
        # Identity warp — recovered displacement at every POI must be
        # numerically zero modulo float noise.
        shape: tuple[int, int, int] = (64, 64, 64)
        pair = make_pair(shape=shape, field=rigid_shift((0.0, 0.0, 0.0)), seed=23)

        _, recovered = _run_pipeline(pair.reference, pair.deformed, window=32, overlap=0.5)

        np.testing.assert_allclose(recovered, 0.0, atol=0.05)
